{% set name = "qgv" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Gepetto/qgv/releases/download/v{{ version }}/qgv-{{ version }}.tar.gz
  sha256: c6dcc26a542ab4a8dd7601c0b1826fcfc0e0e604c161782c0cf368cd0e77daaa

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - doxygen
    - {{ cdt('mesa-libgl-devel') }}       # [linux]
    - {{ cdt('mesa-dri-drivers') }}       # [linux]
    - {{ cdt('libselinux-devel') }}       # [linux]
  host:
    - libboost-devel
    - ffmpeg 4.4
    - graphviz
    - qt-main
    - xcb-util                           # [linux]
    - xcb-util-wm                        # [linux]
    - xcb-util-keysyms                   # [linux]
    - xcb-util-image                     # [linux]
    - xcb-util-renderutil                # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libxdamage                    # [linux]
    - xorg-libsm                         # [linux]
    - xorg-libice                        # [linux]
    - xorg-libxxf86vm                    # [linux]
    - xorg-xf86vidmodeproto              # [linux]

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}

about:
  home: https://github.com/Gepetto/qgv
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Interactive Qt graphViz display
  description: Interactive Qt graphViz display
  doc_url: https://gepettoweb.laas.fr/hpp/hpp-doc/doxygen-html/index.html
  dev_url: https://github.com/Gepetto/qgv

extra:
  recipe-maintainers:
    - ymontmarin
